<?php

declare(strict_types=1);

return [
    [
        'path' => 'accident_csv_renamed/accident_abandoned_victim.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_abandoned_victim',
        'domain_label_el' => 'Εγκατάλειψη θύματος',
        'has_header' => true,
        'code_column' => 'yesnounknown_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'accident_csv_renamed/accident_alcohol.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_alcohol',
        'domain_label_el' => 'Εμπλοκή αλκοόλ',
        'has_header' => true,
        'code_column' => 'yesnounknown_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'accident_csv_renamed/accident_animal.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_animal',
        'domain_label_el' => 'Σύγκρουση με ζώο',
        'has_header' => true,
        'code_column' => 'yesnounknown_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'accident_csv_renamed/accident_events_sequence.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_events_sequence',
        'domain_label_el' => 'Ακολουθία συμβάντων ατυχήματος',
        'has_header' => true,
        'code_column' => 'accidentcollisionevent_id',
        'label_column' => 'description',
        'sort_column' => 'descriptionorder',
        'meta_columns' => ['collisiontype'],
    ],
    [
        'path' => 'accident_csv_renamed/accident_first_collision_event.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_first_collision_event',
        'domain_label_el' => 'Πρώτο συμβάν σύγκρουσης',
        'has_header' => true,
        'code_column' => 'accidentcollisionevent_id',
        'label_column' => 'description',
        'sort_column' => 'descriptionorder',
        'meta_columns' => ['collisiontype'],
    ],
    [
        'path' => 'accident_csv_renamed/accident_gadas_sort.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_gadas_sort',
        'domain_label_el' => 'Ταξινόμηση GADAS',
        'has_header' => true,
        'code_column' => 'cadasaccidenttype_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'accident_csv_renamed/accident_most_harmful_event.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_most_harmful_event',
        'domain_label_el' => 'Πλέον επιβλαβές συμβάν',
        'has_header' => true,
        'code_column' => 'accidentcollisionevent_id',
        'label_column' => 'description',
        'sort_column' => 'descriptionorder',
        'meta_columns' => ['collisiontype'],
    ],
    [
        'path' => 'accident_csv_renamed/accident_narcotics.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_narcotics',
        'domain_label_el' => 'Εμπλοκή ναρκωτικών ουσιών',
        'has_header' => true,
        'code_column' => 'yesnounknown_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'accident_csv_renamed/accident_related_factor.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_related_factor',
        'domain_label_el' => 'Σχετικοί παράγοντες ατυχήματος',
        'has_header' => true,
        'code_column' => 'accidentrelatedfactor_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'accident_csv_renamed/accident_severity.csv',
        'source_scope' => 'accident',
        'target' => 'lookup',
        'domain_code' => 'accident_severity',
        'domain_label_el' => 'Σοβαρότητα ατυχήματος',
        'has_header' => true,
        'code_column' => 'accidentseverity_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],

    [
        'path' => 'road_csv_renamed/road_alignment.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_alignment',
        'domain_label_el' => 'Γεωμετρική χάραξη οδού',
        'has_header' => true,
        'code_column' => 'roadwayalignment_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_construction_zone.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_construction_zone',
        'domain_label_el' => 'Ζώνη κατασκευής ή συντήρησης',
        'has_header' => true,
        'code_column' => 'roadconstructionzone_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_cycle_facilities.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_cycle_facilities',
        'domain_label_el' => 'Υποδομές ποδηλάτου',
        'has_header' => true,
        'code_column' => 'roadcyclefacilities_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_fog.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_fog',
        'domain_label_el' => 'Παρουσία ομίχλης',
        'has_header' => true,
        'code_column' => 'yesnounknown_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_junction.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_junction',
        'domain_label_el' => 'Τύπος διασταύρωσης',
        'has_header' => true,
        'code_column' => 'roadjunction_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_lighting_condition.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_lighting_condition',
        'domain_label_el' => 'Συνθήκες φωτισμού',
        'has_header' => true,
        'code_column' => 'envlightingcondition_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_local_area.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_local_area',
        'domain_label_el' => 'Τοπική περιοχή οδού',
        'has_header' => true,
        'code_column' => 'roadlocalarea_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_pedestrian_facility.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_pedestrian_facility',
        'domain_label_el' => 'Υποδομές πεζών',
        'has_header' => true,
        'code_column' => 'roadpedestrianfacility_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_signaling_factors.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_signaling_factors',
        'domain_label_el' => 'Παράγοντες σηματοδότησης',
        'has_header' => true,
        'code_column' => 'roadsigningfactors_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_sli_contributed_collision.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_sli_contributed_collision',
        'domain_label_el' => 'Συνεισφορά υποδομής περιορισμού ταχύτητας',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_speed_limiting_facility.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_speed_limiting_facility',
        'domain_label_el' => 'Υποδομή περιορισμού ταχύτητας',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_speed_limit_type.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_speed_limit_type',
        'domain_label_el' => 'Τύπος ορίου ταχύτητας',
        'has_header' => true,
        'code_column' => 'roadspeedlimittype_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_strong_winds.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_strong_winds',
        'domain_label_el' => 'Ισχυροί άνεμοι',
        'has_header' => true,
        'code_column' => 'yesnounknown_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_surface.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_surface',
        'domain_label_el' => 'Επιφάνεια οδοστρώματος',
        'has_header' => true,
        'code_column' => 'roadsurfacetype_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_surface_contaminents.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_surface_contaminents',
        'domain_label_el' => 'Ρύποι επιφάνειας οδοστρώματος',
        'has_header' => true,
        'code_column' => 'roadsurfacecontaminents_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_surface_type.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_surface_type',
        'domain_label_el' => 'Τύπος οδού',
        'has_header' => true,
        'code_column' => 'roadcarriagewaytype_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_traffic_signal_control.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_traffic_signal_control',
        'domain_label_el' => 'Έλεγχος φωτεινής σηματοδότησης',
        'has_header' => true,
        'code_column' => 'roadtrafficsignalcontrol_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_traffic_signal_device_functioning.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_traffic_signal_device_functioning',
        'domain_label_el' => 'Λειτουργία συσκευής σηματοδότησης',
        'has_header' => true,
        'code_column' => 'roadtrafficsignaldevicefunctioning_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_trafficway_flow.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_trafficway_flow',
        'domain_label_el' => 'Ροή κυκλοφορίας οδού',
        'has_header' => true,
        'code_column' => 'roadtrafficwayflow_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_transient_factors.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_transient_factors',
        'domain_label_el' => 'Παροδικοί παράγοντες',
        'has_header' => true,
        'code_column' => 'roadtransientfactors_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'road_csv_renamed/road_weather_conditions.csv',
        'source_scope' => 'road',
        'target' => 'lookup',
        'domain_code' => 'road_weather_conditions',
        'domain_label_el' => 'Καιρικές συνθήκες',
        'has_header' => true,
        'code_column' => 'envweathercondition_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],

    [
        'path' => 'vehicle_csv_renamed/_ABS.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_abs',
        'domain_label_el' => 'Σύστημα ABS',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/_ACS.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_acs',
        'domain_label_el' => 'Σύστημα ACS',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/_CDC3.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_cdc3',
        'domain_label_el' => 'Κωδικοποίηση CDC3',
        'has_header' => true,
        'code_column' => 'vehiclecdc3_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => ['code'],
    ],
    [
        'path' => 'vehicle_csv_renamed/_CDC4.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_cdc4',
        'domain_label_el' => 'Κωδικοποίηση CDC4',
        'has_header' => true,
        'code_column' => 'vehiclecdc45_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => ['code', 'impact'],
    ],
    [
        'path' => 'vehicle_csv_renamed/_CSS.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_css',
        'domain_label_el' => 'Σύστημα CSS',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/_ESP.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_esp',
        'domain_label_el' => 'Σύστημα ESP',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/_LDW.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_ldw',
        'domain_label_el' => 'Σύστημα LDW',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/_TCS.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_tcs',
        'domain_label_el' => 'Σύστημα TCS',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_collision_offroad_object.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_collision_offroad_object',
        'domain_label_el' => 'Σύγκρουση με αντικείμενο εκτός οδού',
        'has_header' => true,
        'code_column' => 'vehicleobjectstruckoffroad_id',
        'label_column' => 'description',
        'sort_column' => 'descriptionorder',
        'meta_columns' => ['objectstruckoffroadtype', 'objectstruckoffroaddetail'],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_collision_type.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_collision_type',
        'domain_label_el' => 'Τύπος σύγκρουσης οχήματος',
        'has_header' => true,
        'code_column' => 'vehiclecollisiontype_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_color.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_color',
        'domain_label_el' => 'Χρώμα οχήματος',
        'has_header' => true,
        'code_column' => 'vehiclecolor_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_damage_possible_factor.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_damage_possible_factor',
        'domain_label_el' => 'Πιθανός παράγοντας ζημιάς',
        'has_header' => true,
        'code_column' => 'yesnounknown_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_dangerous_cargo.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_dangerous_cargo',
        'domain_label_el' => 'Επικίνδυνο φορτίο',
        'has_header' => true,
        'code_column' => 'vehiclehazardcargo_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_drive_position.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_drive_position',
        'domain_label_el' => 'Θέση οδήγησης',
        'has_header' => true,
        'code_column' => 'vehicledriveofvehicle_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_drive_wheels.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_drive_wheels',
        'domain_label_el' => 'Κινητήριοι τροχοί',
        'has_header' => true,
        'code_column' => 'vehicledrivenwheels_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_firefighting_equipment_used.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_firefighting_equipment_used',
        'domain_label_el' => 'Χρήση πυροσβεστικού υλικού',
        'has_header' => true,
        'code_column' => 'yesnounknown_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_inspected.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_inspected',
        'domain_label_el' => 'Τεχνικός έλεγχος οχήματος',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_manufacturers.csv',
        'source_scope' => 'vehicle',
        'target' => 'vehicle_manufacturers',
        'domain_code' => null,
        'domain_label_el' => null,
        'has_header' => true,
        'code_column' => 'id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_models.csv',
        'source_scope' => 'vehicle',
        'target' => 'vehicle_models',
        'domain_code' => null,
        'domain_label_el' => null,
        'has_header' => false,
        'code_index' => 0,
        'manufacturer_code_index' => 1,
        'label_index' => 2,
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_on_fire.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_on_fire',
        'domain_label_el' => 'Πυρκαγιά οχήματος',
        'has_header' => true,
        'code_column' => 'vehiclefire_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_roadway_alignment.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_roadway_alignment',
        'domain_label_el' => 'Ευθυγράμμιση οχήματος στο οδόστρωμα',
        'has_header' => true,
        'code_column' => 'vehicleverticalalignment_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_scattered_dangerous_cargo.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_scattered_dangerous_cargo',
        'domain_label_el' => 'Διασπορά επικίνδυνου φορτίου',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_swerved.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_swerved',
        'domain_label_el' => 'Ελιγμός πριν το ατύχημα',
        'has_header' => true,
        'code_column' => 'vehiclemanoeuvreprioraccident_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_trailer.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_trailer',
        'domain_label_el' => 'Ρυμούλκηση/ρυμουλκούμενο',
        'has_header' => true,
        'code_column' => 'yesnounknownna_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
    [
        'path' => 'vehicle_csv_renamed/vehicle_type.csv',
        'source_scope' => 'vehicle',
        'target' => 'lookup',
        'domain_code' => 'vehicle_type',
        'domain_label_el' => 'Τύπος οχήματος',
        'has_header' => true,
        'code_column' => 'vehicletype_id',
        'label_column' => 'description',
        'sort_column' => null,
        'meta_columns' => [],
    ],
];
